### ISSUE TITLE
Debug Jest with current test file doesn't stop at correct breakpoint in VSCode

### ISSUE THREAD

**Issue by trivikr** [jest-community/vscode-jest#372]
_From @trivikr on August 30, 2018 6:48_

## 🐛 Bug Report
Debug Jest with current test file doesn't stop at correct breakpoint in VSCode

## To Reproduce
* Open Jest source code in VSCode (tested in VSCode 1.26.1 on Ubuntu 18.04.1)
* Open any test file (tested with putting breakpoint at on [line 28 of is_valid_path.test.js](https://github.com/facebook/jest/blob/6d3da9be06350bfa7414b609807ebd0cbdf0c416/packages/jest-cli/src/lib/__tests__/is_valid_path.test.js#L28))
* Go to debug mode in VSCode, and click "Debug Jest with current test file"
* Notice that debugger stops at line 22 instead

## Screen Recording
[![Debug Jest with current test file not stopping at correct breakpoint](https://img.youtube.com/vi/VZUJyI3GeYY/0.jpg)](https://www.youtube.com/watch?v=VZUJyI3GeYY)

## Expected behavior
Debugger stops at Line 28

_Copied from original issue: facebook/jest#6918_

**Comment by trivikr** [comment]
_From @SimenB on August 30, 2018 10:22_

This works in Chrome and IntelliJ, so it's an issue with vs code, not Jest (maybe https://github.com/jest-community/vscode-jest?).

![image](https://user-images.githubusercontent.com/1404810/44845910-23558080-ac4f-11e8-858a-b85850d18131.png)

![image](https://user-images.githubusercontent.com/1404810/44845924-2badbb80-ac4f-11e8-9f8a-bbae878e1da2.png)

**Comment by connectdotz** [comment]
jest uses flow, and vscode uses [sourcemaps](https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_source-maps) to debug these transpiled codes. There are a few suggestions on how to debug flow in vscode, such as  [here](https://github.com/flowtype/flow-for-vscode#debugger-configuration). 

But for your use case, I found a simple line in `.babelrc` worked just fine without the full sourcemaps support:
```
"retainLines": true
```

**Comment by Morikko** [comment]
I fixed it by setting `"sourceMaps": false,` in `launch.json`

**Comment by trivikr** [comment]
Thank you @connectdotz, I've posted fix in Jest repo at https://github.com/facebook/jest/pull/6985

Thank you @Morikko for sharing another option. I tried it, but it didn't work in some situations (like with file `notify-reporter.test.js`)

**Comment by trivikr** [comment]
The fix was merged in https://github.com/facebook/jest/commit/68eb9a232dcbd4ecf85bb1f0bdad5cb850dff81a

**Comment by Morikko** [comment]
Yes, I also had trouble with the previous solution. Breakpoints were in the right place but actually executing code at another place.

I added `"runtimeArgs": ["-r", "flow-remove-types/register"],` to my project configuration (`launch.json`) but it still doesn't work. My project is not using flow but standard javascript.
I am calling jest from `./node_modules/jest/bin/jest.js`.

Did you do other things ?

**Comment by trivikr** [comment]
This issue was raised in Jest's code base, and it was fixed with adding `"runtimeArgs": ["-r", "flow-remove-types/register"]` in launch.json in commit https://github.com/facebook/jest/commit/68eb9a232dcbd4ecf85bb1f0bdad5cb850dff81a
